name: 'Compiled Hugo'
description: 'Build Hugo to static web page, then store artifact'
inputs:
  artifact-name:
    description: 'Name of artifact'
    required: true
  directory:
    description: 'Directory of hugo project'
    required: true
  retention-day:
    description: 'Artifact is retained for 1 days by default'
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'
        extended: true
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.152.0
      with:
        ruby-version: 3.2
    
    - name: Install asciidoctor
      shell: bash
      run: gem install asciidoctor

    - name: Build hugo
      shell: bash
      run: hugo
      working-directory: ${{ inputs.directory }}

    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.directory}}/dist
        retention-days: ${{ inputs.retention-day }}
