name: 'Update version'
description: 'Updates the version for the local maven repository as well as all Eclipse SET dependencies in the specified target platform'
inputs:
  version:
    description: 'Release version. Format: <major>.<minor>.<patch>(.<tag>)'
    required: true
  target:
    description: 'Path to target platform'
    required: true
  pom:
    description: 'Path to pom.xml'
    required: false
    default: 'pom.xml'

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: eclipse-set/build/.github/actions/setup-java@main
      
    - name: Set Maven Version
      shell: bash
      run: mvn -f ${{ inputs.pom }} -B tycho-versions:set-version -DnewVersion=${{ inputs.version }}

    - name: Install xmlstarlet
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xmlstarlet

    - name: Update target platform
      shell: bash
      run: |
        xmlstarlet ed --inplace \
          -u "target/locations/location/dependencies/dependency[groupId='org.eclipse.set']/version" \
          -v '${{ inputs.version }}' \
          -u "/target/locations/location/repositories/repository/url[starts-with(., 'https://maven.pkg.github.com/eclipse-set/')]" \
          -x 'concat("https://maven.pkg.github.com/${{ github.repository_owner }}/", substring-after(., "https://maven.pkg.github.com/eclipse-set/"))' \
          ${{ inputs.target }}

    - name: Update DEPENDENCIES
      uses: eclipse-set/build/.github/actions/update-dependency-file@main
      with:
        pom: ${{ inputs.pom }}