name: 'Update DEPENDENCIES file'
description: 'Updates the DEPENDENCIES file'
inputs:
  pom:
    description: 'pom.xml path'
    required: false
    default: 'pom.xml'

runs: 
  using: "composite"
  steps:
    - name: Set up Java
      uses: eclipse-set/build/.github/actions/setup-java@main

    - name: Process maven dependencies
      shell: bash
      run: mvn -f ${{ inputs.pom }} -U -B -ntp -Dtycho.target.eager=true dependency:list -DappendOutput=true -DoutputFile=${{ github.workspace }}/maven.deps

    - name: License check
      shell: bash {0} # do not fail-fast
      run: |
        wget -nv -O ../dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
        java -jar ../dash.jar ${dashArgs} -summary DEPENDENCIES $(find . '(' -name "*.deps" -o -name "package-lock.json" ')' -type f -exec sh -c 'echo "$0"' {} \;)
        rm -rf ${{ github.workspace }}/maven.deps
