pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/deploy-release/kubernetes.yaml'
        }
    }

    options {
        timeout(time: 20, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    parameters {
        string description: 'Release Version', name: 'ReleaseVersion', trim: true
    }


    stages {
        stage('Sign Release') {
            steps {
                container('github') {
                    withCredentials([string(credentialsId: 'github-bot-token', variable: 'GITHUB_TOKEN')]) {
                        sh "gh release download -R eclipse-set/set v${params.ReleaseVersion} -p 'unsigned-Eclipse-SET-*'"
                        sh 'unzip -q SET-*.zip -d set'
                        dir('set')
                        {
                            sh "find . -name 'org.eclipse.set*.jar' | xargs -I % curl --fail -o % -F file=@% https://cbi.eclipse.org/jarsigner/sign"   
                            sh "zip -r Eclipse-SET-${params.ReleaseVersion}.zip ."
                            archiveArtifacts artifacts: "Eclipse-SET-${params.ReleaseVersion}.zip", followSymlinks: false
                        }
                    }
                }
            }
        }
    }
}
