name: 'Setup Asciidoctor'
description: 'Installs Asciidoctor, including Hugo and Ruby'

runs:
  using: 'composite'
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
      with:
        hugo-version: '0.101.0'
        extended: true
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
      with:
        ruby-version: 3.2
    
    - name: Install Asciidoctor
      shell: bash
      run: gem install asciidoctor
