name: 'Setup Asciidoctor'
description: 'Installs Asciidoctor, including Hugo and Ruby'

runs:
  using: 'composite'
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
      with:
        hugo-version: '0.101.0'
        extended: true
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
      with:
        ruby-version: 3.2
    
    - name: Install Asciidoctor
      shell: bash
      run: gem install asciidoctor
