# This workflow will build and push Docker images into ghcr.io/eclipse-set
name: 'Build and push Docker image'

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login into the container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Rust image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          file: ./docker/rust/Dockerfile
          push: true
          tags: ghcr.io/eclipse-set/rust-x86_64-pc-windows-gnu:latest
